@extends('layouts.base')
@section('content')
    <index-component
    :product='@json($product)'
    :images='@json($product->images)'
    :attributes='@json($product->attributes)'
    :link='@json($link)'
    :globalLink='@json($_SERVER['REQUEST_URI'])'
    ></index-component>
@endsection
